import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/layout/Header'
import { inter, jakarta, poppins } from '@/fonts/fonts'
import Footer from '@/components/layout/Footer'

export const metadata: Metadata = {
  title: 'Cripton',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakarta.variable} ${inter.variable} ${poppins.variable}`}>
        <Header />
        <main className="flex flex-col items-center ">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
